### PR TITLE
Dropbox support

### PR DESCRIPTION
**Pull request by aslakhellesoy**
This PR adds Dropbox support. The code was written by @cartuchogl in cartuchogl/authom@386642b2fbbb7d7d08f77bedc8c4007d1e9d1fee

I have added links in the two examples and set up an app on Dropbox so you can try it out.

Would be great to have in the next release.

### CODE REVIEW

**Comment by jed** [comment]
awesome. but i apparently can't test it because tokens are limited during development mode... is there some whitelist you can add me to so that i can give it a try?

**Comment by aslakhellesoy** [comment]
Try again. I had to allow others to connect over at https://www.dropbox.com/developers/apps - 5 people are allowed since this is not a prod app.

**Comment by jed** [comment]
tried it, and it worked. pulling and updating npm now...

**Comment by jed** [comment]
@aslakhellesoy, can you add dropbox to the docs in the README.md?

**Comment by aslakhellesoy** [comment]
Done. See #29.

**Pull request merged**
