### PR TITLE
Support Stripe Connect

### PR DESCRIPTION
**Pull request by recipher**
Added Stripe service code
Updated OAuth2 code deal with Stripe-specific requirements
Updated readme

### CODE REVIEW

**Comment by recipher** [comment]
I'll do the Express.js fixes once this has been approved. I don't do pull requests too often, so I'm not sure of the best approach to avoid a merged PR (which is what happened earlier).

**Comment by recipher** [comment]
There's another commit coming down the pipe. Unfortunately, it's some more Stripe-specific code to deal with some data which is required from the code request but not exposed in the user data.

**Comment by jed** [comment]
yeah, stripe-specific code isn't optimal, but i'd rather have stripe in now than wait for a refactor.

**Comment by recipher** [comment]
Thanks. Me too.

**Pull request merged**
