### PR TITLE
37 Signals Support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jed** [comment]
yikes, couldn't get this to merge so did it manually. coming up.

**Comment by ghost** [comment]
I will sort it.. Just forgot to commit and pulling the updates.. My bad

**Comment by jed** [comment]
ha, too late! do you want to take a crack at oauth1 starting w/ twitter?

**Comment by ghost** [comment]
I did it last april for my iOS app TweetyPop, so that means it should be easy or I am going to say no-freeking-way ;)  Let me look at that link you sent earlier. BTW last time I was up at twitter for  dev gathering, oAuth2 support was asked for alot..

**Comment by jed** [comment]
yeah, it looks like a mess. oauth2 is cake. let me know if you're gonna try, otherwise i might try it myself.

**Pull request closed without merging**
