### PR TITLE
added Dwolla.com to the growing list :)

### PR DESCRIPTION
**Pull request by ghost**
https://www.dwolla.com/developers

### CODE REVIEW

**Comment by jed** [comment]
cool, would you mind updating the README too?

**Comment by ghost** [comment]
Yeah no problem

**Comment by ghost** [comment]
Done and pull request sent.

**Comment by ghost** [comment]
So I forgot the icon (which I have since added) but I am being blocked from sending a pull request due to the existing one. Odd

**Comment by jed** [comment]
okay, merged. can you try again?

**Comment by ghost** [comment]
Oddly it looked like it combined the pull requests automatically. Icon shows up 

## 

Node Biscut
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jed** [comment]
ah, cool. i think the returns on oauth2 have diminished for now. taking a look at oauth now, but it seems pretty hairy, and i'd only be doing it for twitter.

**Comment by ghost** [comment]
nod...   I am about to embark (for fun and pain.. and a need) on doing a oauth2 provider .. going to see (as a learning experience) what it takes to fork https://github.com/ammmir/node-oauth2-provider and put it ontop of flatiron

**Pull request merged**
