### PR TITLE
Allow authom users to specify fields for facebook

### PR DESCRIPTION
**Pull request by pspeter3**
This means that people can request picture or some other non standard fields.

### CODE REVIEW

**Comment by pspeter3** [comment]
Updated to add the brackets

**Comment by jed** [comment]
would you mind adding a description to the README as well?

**Comment by pspeter3** [comment]
Hey @jed do I need to anything else to get a ship it :squirrel:?

**Comment by jed** [comment]
nope! thanks, @pspeter3!

**Pull request merged**
