### PR TITLE
Add ability to register custom services to Authom

### PR DESCRIPTION
**Pull request by ovaillancourt**
This pull adds the `registerService` method that allows someone to register an authom-compatible service that is too specific to go into the core services folder. (For example a business-specific login/pass system.)

This also allows to override the behavior of existing "core" services.

Also added documentation + usage example.

### CODE REVIEW

**Comment by deedubs** [comment]
+1 to this.  Seems like a more efficient way to allow people to add services. I would almost like to see all the 'services' registered in this way.

**Comment by deedubs** [comment]
@jed Is there something we can do to improve this PR to get it accepted? Or are you against the idea outright?

**Comment by jed** [comment]
it's a good idea, just fell through the cracks. merged, about to update npm.

**Comment by deedubs** [comment]
Thanks Jed!

Sent from my iPhone

On 2012-11-07, at 10:00 PM, Jed Schmidt notifications@github.com wrote:

it's a good idea, just fell through the cracks. merged, about to update npm.

—
Reply to this email directly or view it on
GitHubhttps://github.com/jed/authom/pull/15#issuecomment-10174199.

**Comment by jed** [comment]
don't thank me, thank @ovaillancourt!

**Comment by ovaillancourt** [comment]
haha, well thanks jed anyways! Man I had completely forgot about that pull too.

**Pull request merged**
