### PR TITLE
Added mechanism for self-authenticated clients

### PR DESCRIPTION
**Pull request by thanpolas**
Some providers (like Facebook) offer javascript SDKs that allow for a complete client side authentication. In those cases, the client performs all the authentication steps without the server ever getting touched.

For such cases the `verifyAuth` mechanism is provided. After the client-side authentication completes, and the _Access Token_ is available, we can perform a POST request to the server with the _Access Token_ in order to:
1. Inform the server that we are authenticated with a provider
2. Have the server validate with the provider the authentication
3. Get back a proper response from the server with our auth logic (our local user data object)

By default the `verifyAuth` mechanism is **turned off**.

### CODE REVIEW

**Comment by jed** [comment]
hmmm, i'm not convinced this is worth it.

this library is for aggregating server authentication, from which a client auth workflow is significantly different. i'm a big fan of one thing done right, and am not sure the marginal functionality added outweighs the more complicated API with additional endpoint and slightly awkward parameters (like `verifyAuthAccessTokenParam`).

wouldn't it be better to have this in a separate library?

**Comment by thanpolas** [comment]
Never mind the style and param naming,

How do you respond to this reality? There is only one way for the server to verify / validate a client side authentication and that is to perform an API call to the provider with the access token the client provides. So one would expect / needs:
1. His auth library to handle, well, authentication
2. His auth library to be aware of the auth state (keep the access token)
3. His auth flow to work as expected ('auth' event trigger)

Have a second library wrapping authom?

**Comment by thanpolas** [comment]
@jed verdict?

**Comment by jed** [comment]
i don't deny the reality, but i just don't see the win in complicating the library... are there really apps that do both client- AND server-side authentication?

if there's a piece of this library that should be factored out to make other scenarios possible, i think it makes more sense to explore that.

**Comment by thanpolas** [comment]
uhmmm i am confused as to where this discussion is heading, a plain **No** would suffice... 

If the core question is:

> are there really apps that do both client- AND server-side authentication?

The answer to that is: YES there are. The flow is provided by [facebook](https://developers.facebook.com/docs/reference/javascript/FB.login/),  [LinkedIn](https://developer.linkedin.com/documents/inauth-inevent-and-inui), [Google+](http://code.google.com/p/google-api-javascript-client/wiki/Authentication), to name a few, so it's pretty much out there.

If the implementation and the new API commands are what bothers you, then by all means do a code review and point out how you want things done. I'd be more than happy to provide followup commits.

If however you believe that an auth library should not include this flow because it will complicate the library, then i'd implore you to give a fresh, new look, as you are not doing it justice.

**Comment by jed** [comment]
the reason i haven't said no is because i am open to being convinced. this has yet to happen.

i know the flow you describe is provided, i just don't know of any apps that use client-side AND server-side authentication at the same time. it still seems better to build your client-side lib and use authom as a dependency.

**Comment by deedubs** [comment]
I'm going to have to agree that it doesn't seem worth the complication

**Comment by jed** [comment]
agreed. closing.

**Pull request closed without merging**
