### PR TITLE
Added foursquare auth

### PR DESCRIPTION
**Pull request by ghost**
Added support for foursquare authentication. Also changed the server to use process.env.PORT  vs the default 80 to allow it to run in (as an example) heroku

### CODE REVIEW

**Comment by jed** [comment]
awesome. many thanks, @nodebiscut!

**Comment by ghost** [comment]
I really liked the simplicity of the library and its focus. Expect a few more out of me

I do have a instagram one in the works as well, but they seem to have an issue with encoded redirect_uri's 

## 

Node Biscut
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jed** [comment]
this is awesome to hear. eventually we should probably refactor a lot of the oauth2 logic into its own library, shouldn't be too hard. will stay tuned for more!

**Comment by jed** [comment]
okay, refactored. should make it even easier to bang out new services.

**Pull request merged**
