### PR TITLE
Add fields selector and respond format options for LinkedIn + Explanations

### PR DESCRIPTION
**Pull request by shinecita**
This will allow the authom users to:

Include in the linkedin response the fields they are interested in, and also they they be able to select the format of the response.

Also explanations included now.

### CODE REVIEW

**Comment by shinecita** [comment]
Sorry @jed Don't know what went wrong maybe my last commit which was irrelevant and I've reversed.

**Comment by jed** [comment]
hmmm, still the same problem... any way you could start over with a fresh commit from master?

**Comment by shinecita** [comment]
I did the merge already, shouldnt be a problem now.

**Comment by jed** [comment]
cool, thanks @shinecita.

**Pull request merged**
