### PR TITLE
Initial Pass at test suite

### PR DESCRIPTION
**Pull request by deedubs**

### CODE REVIEW

**Comment by jed** [comment]
whoa, was just noodling how to test such a library reliably. would you mind squashing your commits so we can grok them better?

**Comment by deedubs** [comment]
Sure.  I haven't got to testing the auth stuff directly, its currently more of a smoke test, but I plan on mocking out https? so I can test without external dependencies.

**Comment by jed** [comment]
oh, nice. will be watching with anticipation!

**Comment by deedubs** [comment]
I think I prematurely opened this PR I'll let it bake a little more and then so a proper cleaned up version.  Sorry @jed.

**Comment by jed** [comment]
no worries, take your time!

## 

heads up: my email address is now where@jed.is, so plan accordingly.

**Pull request closed without merging**
